all:
  vars:
    ansible_user: ubuntu
  children:
    web:
      hosts:
        web-1.ru-central1.internal:
        web-2.ru-central1.internal:
    elastic:
      hosts:
        elastic.ru-central1.internal:
    kibana:
      hosts:
        kibana.ru-central1.internal:
    zabbix:
      hosts:
        zabbix.ru-central1.internal:
